### ISSUE TITLE
logs.dir in userdata.properties - set by Sakuli

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#110]
Sakuli always sets this global property to a suite specific value. 
This means that while debugging Sahi via the controller, logs are written to a suite folder which has nothing to do with the debug session.

**Comment by simonmeggle** [comment]
(Is this setting possible with a JVM parameter ? )

**Comment by toschneck** [comment]
The value of `logs.dir` will be reset from Sakuli after the test execution to value, which is defined before the test execution. Only if the sakuli execution will killed hardly by killing the processes the value won`t be restored. Due to the architecture of Sahi, there is currently no other way to do this. If someone have this problem, he have to reset the value to `logs` manually
