### ISSUE TITLE
introduce sakuli.forwarder.gearman.nagios.service_description

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#188]
(instead of testsuite.id)

**Comment by toschneck** [comment]
`NagiosCheckResultBuilder` should use the service_description from the `GearmanProperties` if the property is set. If no property is set use the teststuite id. The default behavior should still use the testsuite id. 
@simonmeggle should this be also done for the DB forwarder?

**Comment by simonmeggle** [comment]
Perfect. Yes, and also the Icinga forwarder I think.

**Comment by christophd** [comment]
Done with introducing sakuli.forwarder.gearman.nagios.service_description property for NagiosCheckResultBuilder.

I do not see where to add this same logic to Icinga2CheckResultBuilder because it is building the Icinga2Request and there is no such property to set.

DBForwarder is saving the pure testsuite data. We could introduce a new property testsuite.description but then testsuite.description should be the default value for gearman forwarder instead of testsuite.id.

**Comment by simonmeggle** [comment]
DBForwarder: not neccessary 
IcingaForwarder: sakuli.forwarder.icinga2.nagios.service_description=${testsuite.id}

**Comment by toschneck** [comment]
To solve this point:
> Provide for cl the js-call to adjust this property at runtime like the following example for the screenshot action propery: Packages.org.sakuli.loader.BeanLoader.loadBaseActionLoader().getActionProperties().setTakeScreenshots(false);

Issue #227 have been created
