### ISSUE TITLE
Rewrite encryption feature to use a master key instead of MAC address

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#197]
Sakuli test suites not transportable to another host without some modifications (e.g. localization folder with symlink to hostname folder). 

-> Search for a way that encrypted strings can be decrypted host independent.

**Comment by simonmeggle** [comment]
Proposal: new Property for the location of JCEKS Keystore (http://www.pixelstech.net/article/1420439432-Different-types-of-keystore-in-Java----JCEKS) to store passwords safely. 
Sakuli could load the needed passwords on the fly from there.

**Comment by toschneck** [comment]
Due to the fact that an JCEKS keystore won't increase the security, we should implement the following approach:
* Change the encryption logic from interface to an environment variable based master key implementation
  * Class to adjust:  https://github.com/ConSol/sakuli/blob/master/src/core/src/main/java/org/sakuli/actions/environment/CipherUtil.java
    * remove network interface logic and properties
    * read environment var `SAKULI_ENCRYPTION_KEY` (base64 encoded key, to avoid java zero bytes)
    * Use `AES/CBC/PKCS5Padding` algorithm
  * Maybe refactor the following class with a common class: https://github.com/ConSol/sakuli/blob/master/src/core/src/main/java/org/sakuli/services/forwarder/gearman/crypt/Aes.java
* Change `sakuli encrypt` cli of https://github.com/ConSol/sakuli-go-wrapper
  * remove interface logic
  * add command to generate a random master key
  * add option to set the master key on `sakuli encrypt topsecret`
  * adjust example output on `sakuli - help`
